services:
  - type: web
    name: 4giifts-gift-generator
    env: node
    region: ohio
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    plan: free
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
